baseURL: "https://isopov.github.io/"
languageCode: "en-us"
title: "Ivan Sopov blog"
theme: "hugo-PaperMod"
params:
  socialIcons:
    - name: github
      url: "https://github.com/isopov"
    - name: twitter
      url: "https://twitter.com/i_sopov"
    - name: linkedin
      url: "https://www.linkedin.com/in/ivan-sopov-74623b28/"
